/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;
import mondrian.olap.MondrianDef.SQL;

/**
 *
 * @author Jelson Fernandes
 */
public class CadastroProdutos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    //criando variaveis especiais para conexão com o banco
    //prepared statement e resultSet são frameworks do pacote java.sql
    //e servem para preparar eexecutar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    ModeloProduto mod = new ModeloProduto();
    ControleProduto control = new ControleProduto();
    ConectaBanco conexaopesquisa = new ConectaBanco ();

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
         getContentPane().setBackground(Color.white);
        conexao = ModuloConexao.conector();

        preenchercomb();

    }

    public void preenchercomb() {
        String sql = "select*from tbfornecedores order by nome_fornecedor";
        try {
            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            rs.first();
            jComboBoxFornecedor.removeAllItems();
            do {
                jComboBoxFornecedor.addItem(rs.getString("nome_fornecedor"));
            } while (rs.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher a Combbox! \nERRO:" + e);
        }
    }

    public void preencherTabela(String sql) {

        // conexao = ModuloConexao.conector();
        //outro
        ArrayList dados = new ArrayList();
        //jfAjustaData parcelas=new AjustaData();

        String[] Colunas = new String[]{"PRODUTO", "QUANTIDADE", "PREÇO COMPRA", "PREÇO VENDA", "ID FORNECEDOR"};

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            do {
                dados.add(new Object[]{rs.getString("nome_produto"), rs.getString("quantidade"), rs.getString("Preco_Compra"), rs.getString("Preco_venda"), rs.getString("id_fornecedor")});
            } while (rs.next());

            // String foundType = rs.getString(1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!|nERRO:" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableProduto.setModel((TableModel) modelo);
        jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTableProduto.getColumnModel().getColumn(0).setResizable(false);
        jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableProduto.getColumnModel().getColumn(1).setResizable(false);
        jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableProduto.getColumnModel().getColumn(2).setResizable(false);
        jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableProduto.getColumnModel().getColumn(3).setResizable(false);
        jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableProduto.getColumnModel().getColumn(4).setResizable(false);

        //Reorganizando o cabeçalho 
        jTableProduto.getTableHeader().setReorderingAllowed(false);
        jTableProduto.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldQuant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecCompr = new javax.swing.JTextField();
        jTextFieldPrecVend = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesq = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("       CADASTRO DE PRODUTOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Codigo");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCod.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        jTextFieldCod.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Produto");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNome.setDisabledTextColor(javax.swing.UIManager.getDefaults().getColor("FormattedTextField.caretForeground"));
        jTextFieldNome.setEnabled(false);

        jTextFieldQuant.setDisabledTextColor(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleForeground"));
        jTextFieldQuant.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Quantidade");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Preço de Compra");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldPrecCompr.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        jTextFieldPrecCompr.setEnabled(false);

        jTextFieldPrecVend.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        jTextFieldPrecVend.setEnabled(false);
        jTextFieldPrecVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecVendActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Preço de Venda");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Fornecedor");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFornecedorActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCanc.setText("Cancelar");
        jButtonCanc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCanc.setEnabled(false);
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });

        jButtonPesq.setText("Pesquisar");
        jButtonPesq.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqActionPerformed(evt);
            }
        });

        jButton7.setText("Sair");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableProduto.setBackground(new java.awt.Color(0, 255, 204));
        jTableProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProduto.setForeground(new java.awt.Color(0, 0, 102));
        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuant, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecCompr, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecVend, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFornecedor, 0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCod)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNome)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldQuant)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jTextFieldPrecVend))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jComboBoxFornecedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrecCompr)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPesquisar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        mod.setFornecedor((String) jComboBoxFornecedor.getSelectedItem());
        mod.setNomeProduto(jTextFieldNome.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecCompr.getText()));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecVend.getText()));
        mod.setQuatProduto(Integer.parseInt(jTextFieldQuant.getText()));
        control.inserirProduto(mod);
        jButtonNovo.setEnabled(true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuant.setEnabled(!true);
        jTextFieldPrecCompr.setEnabled(!true);
        jTextFieldPrecVend.setEnabled(!true);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQuant.setText(null);
        jTextFieldPrecCompr.setText(null);
        jTextFieldPrecVend.setText(null);
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCanc.setEnabled(!true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqActionPerformed
        // TODO add your handling code here:

        mod.setPesquisa(jTextFieldPesquisar.getText());
        ModeloProduto model = control.buscaProduto(mod);
        jTextFieldCod.setText(String.valueOf(model.getIdProduto()));
        jTextFieldNome.setText(model.getNomeProduto());
        jTextFieldQuant.setText(String.valueOf(model.getQuatProduto()));
        jTextFieldPrecCompr.setText(String.valueOf(model.getPrecoCompra()));
        jTextFieldPrecVend.setText(String.valueOf(model.getPrecoVenda()));
        jComboBoxFornecedor.setSelectedItem(model.getFornecedor());
        jTextFieldNome.setEnabled(true);
        jTextFieldQuant.setEnabled(true);
        jTextFieldPrecCompr.setEnabled(true);
        jTextFieldPrecVend.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        preencherTabela("select*from tbprodutos where nome_produto like'%" + jTextFieldPesquisar.getText() + "%'");


    }//GEN-LAST:event_jButtonPesqActionPerformed

    private void jTextFieldPrecVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecVendActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        mod.setIdProduto(Integer.parseInt(jTextFieldCod.getText()));
        mod.setFornecedor((String) jComboBoxFornecedor.getSelectedItem());
        mod.setNomeProduto(jTextFieldNome.getText());
        mod.setPrecoCompra(Float.parseFloat(jTextFieldPrecCompr.getText()));
        mod.setPrecoVenda(Float.parseFloat(jTextFieldPrecVend.getText()));
        mod.setQuatProduto(Integer.parseInt(jTextFieldQuant.getText()));
        control.editaProduto(mod);
        jButtonNovo.setEnabled(true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuant.setEnabled(!true);
        jTextFieldPrecCompr.setEnabled(!true);
        jTextFieldPrecVend.setEnabled(!true);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQuant.setText(null);
        jTextFieldPrecCompr.setText(null);
        jTextFieldPrecVend.setText(null);
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCanc.setEnabled(!true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        mod.setIdProduto(Integer.parseInt(jTextFieldCod.getText()));
        control.excluirProduto(mod);
        jButtonNovo.setEnabled(true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuant.setEnabled(!true);
        jTextFieldPrecCompr.setEnabled(!true);
        jTextFieldPrecVend.setEnabled(!true);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQuant.setText(null);
        jTextFieldPrecCompr.setText(null);
        jTextFieldPrecVend.setText(null);
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCanc.setEnabled(!true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(true);
        jTextFieldQuant.setEnabled(true);
        jTextFieldPrecCompr.setEnabled(true);
        jTextFieldPrecVend.setEnabled(true);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQuant.setText(null);
        jTextFieldPrecCompr.setText(null);
        jTextFieldPrecVend.setText(null);
        jButtonSalvar.setEnabled(true);

        jButtonNovo.setEnabled(false);
        jButtonCanc.setEnabled(true);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(!true);
        jTextFieldQuant.setEnabled(!true);
        jTextFieldPrecCompr.setEnabled(!true);
        jTextFieldPrecVend.setEnabled(!true);
        jTextFieldCod.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldQuant.setText(null);
        jTextFieldPrecCompr.setText(null);
        jTextFieldPrecVend.setText(null);
        jButtonSalvar.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCanc.setEnabled(!true);
    }//GEN-LAST:event_jButtonCancActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        // TODO add your handling code here:
         conexao = ModuloConexao.conector();
        String nome_produto = "" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0);
       
         conexao = ModuloConexao.conector();
        String sql = "select*from tbprodutos where nome_produto='" + nome_produto + "'";
        try {
            pst = conexao.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
            
            jTextFieldCod.setText(String.valueOf(rs.getInt("id_produto")));
            jTextFieldNome.setText(rs.getString("nome_produto"));
            jTextFieldQuant.setText(String.valueOf(rs.getInt("quantidade")));
            jTextFieldPrecCompr.setText(String.valueOf(rs.getFloat("Preco_compra")));
            jTextFieldPrecVend.setText(String.valueOf(rs.getFloat("Preco_venda")));
             setarCampos("select*from tbfornecedores where id_fornecedor="+rs.getInt("id_fornecedor"));
          
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao setar os campos!|nERRO:" + ex);
        }
        


    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFornecedorActionPerformed
public void setarCampos(String sql){
     conexao = ModuloConexao.conector();
        try {
            
           
            pst = conexao.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
          rs.first();
           jComboBoxFornecedor.setSelectedItem(rs.getString("nome_fornecedor"));
//             JOptionPane.showMessageDialog(null, "id_fornecedor");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pegar o ID !|nERRO:" + ex);
        }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    public static javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesq;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPrecCompr;
    private javax.swing.JTextField jTextFieldPrecVend;
    private javax.swing.JTextField jTextFieldQuant;
    // End of variables declaration//GEN-END:variables
}
