/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jelson Fernandes
 */
public class ImprimirCadastro extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String nome, nif, endereco, fone, email;

    /**
     * Creates new form ImprimirCadastro
     * @param codCad
     */
    public ImprimirCadastro(int codCad) {
        initComponents();
        conexao = ModuloConexao.conector();
         try {
            
            String sql=("select*from tbalunos where idaluno="+codCad);
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            jTextFieldID.setText(String.valueOf(codCad));
            jTextFieldNome.setText(rs.getString(2));
                    jTextFieldClasse.setText(rs.getString(3));
                    jTextFieldTurno.setText(rs.getString(13));
                    jTextFieldTurma.setText(rs.getString(16));
                    jTextFieldTurma1.setText(rs.getString(17));
                    jTextFieldSala.setText(rs.getString(14));
                    jTextFieldSala1.setText(rs.getString(15));
                    jTextFieldValor.setText(rs.getString(10) + "KZ ");
//            jTextFieldNome.setText(String.valueOf(("1")));
//            jTextFieldClasse.setText(String.valueOf(("classealuno")));
//            jTextFieldTurno.setText(String.valueOf(("turno")));
//            jTextFieldTurma.setText(String.valueOf(("turman")));
//            jTextFieldTurma1.setText(String.valueOf(("turmal")));
//            jTextFieldSala.setText(String.valueOf(("salan")));
//            jTextFieldSala1.setText(String.valueOf(("salal")));
//            jTextFieldValor.setText(String.valueOf(("Valorinscr")));
            //insert into tbalunos(nomealuno,classealuno,endealuno,fonealuno,emailaluno,encarregaluno,nascaluno,localnascaluo,Valorinscr,nomeimagem,imagem,turno,salan,salal,turman,turmal
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " Erro ao Iniciar o Form!\nERRO" + ex);
        }
    

    }

    
       
    private void pesquisar_aluno() {

        try {

            // a linha abaixo cria uma caixa de entrada do tipo JOption Pane
            String num_aluno = JOptionPane.showInputDialog("Número de Cadastro");
            String sql = "select*from tbalunos where idaluno=" + num_aluno;
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            try {
                pst = conexao.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {

                    // File file = archivo.getSelectedFile();
                    jTextFieldID.setText(rs.getString(1));
                    jTextFieldNome.setText(rs.getString(2));
                    jTextFieldClasse.setText(rs.getString(3));
                    jTextFieldTurno.setText(rs.getString(13));
                    jTextFieldTurma.setText(rs.getString(15));
//                    jTextFieldTurma1.setText(rs.getString(17));
                    jTextFieldSala.setText(rs.getString(14));
//                    jTextFieldSala1.setText(rs.getString(15));
                    jTextFieldValor.setText(rs.getString(9) + "KZ ");

                    // txtAluPesquisar.setEnabled(false);
                    //  tblContrato.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Aluno não Cadastrado");
                }

            } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e) {
                JOptionPane.showMessageDialog(null, "Nº de Cadastro Inválido");
                // System.out.println(e);
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, e2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ImprimirCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldClasse = new javax.swing.JTextField();
        jTextFieldTurno = new javax.swing.JTextField();
        jTextFieldTurma = new javax.swing.JTextField();
        jTextFieldSala = new javax.swing.JTextField();
        jTextFieldSala1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonGerar = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonImpr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldTurma1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Classe");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Turno");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Turma");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sala");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Valor");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldID.setEnabled(false);

        jTextFieldNome.setEnabled(false);

        jTextFieldClasse.setEnabled(false);

        jTextFieldTurno.setEnabled(false);

        jTextFieldTurma.setEnabled(false);

        jTextFieldSala.setEnabled(false);

        jTextFieldSala1.setEnabled(false);

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea);

        jButtonGerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGerar.setText("GERAR FACTURA");
        jButtonGerar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonImpr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonImpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/blueprinter.png"))); // NOI18N
        jButtonImpr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/search.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldTurma1.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Turma");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldValor.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sala");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jTextFieldTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(13, 13, 13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(7, 7, 7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(13, 13, 13)))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSala, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTurma1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jTextFieldSala1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jTextFieldClasse, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                                .addGap(104, 104, 104)))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImpr, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImpr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        // TODO add your handling code here:

       
        // String dataSistema = String.valueOf(nome);

       Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        jTextArea.setText(formatador.format(data));
        jTextArea.setText(jTextArea.getText() + "\n" + data + "\n\n");
       
        jTextArea.setText(jTextArea.getText() + "===============RECIBO DE CADASTRO DO ALUNO===============   \n\n\n");
        jTextArea.setText(jTextArea.getText() + "EMPRESA:   " + nome + "\n");
        jTextArea.setText(jTextArea.getText() + "NIF:       " + nif + "\n");
        jTextArea.setText(jTextArea.getText() + "ENDEREÇO:  " + endereco + "\n");
        jTextArea.setText(jTextArea.getText() + "EMAIL:     " + email + "\n");
        jTextArea.setText(jTextArea.getText() + "TELEFONE:  " + fone + "\n\n");
  jTextArea.setText(jTextArea.getText() + "=========================================================  \n\n\n");
        jTextArea.setText(jTextArea.getText() + "Nome do Aluno:                 " + jTextFieldNome.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Classe:                        " + jTextFieldClasse.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Turno:                         " + jTextFieldTurno.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Turma Nº:                      " + jTextFieldTurma.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Turma Alfab:                    " + jTextFieldTurma1.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Sala Nº:                       " + jTextFieldSala.getText() + "\n\n");
//        jTextArea.setText(jTextArea.getText() + "Sala Alfab:                    " + jTextFieldSala1.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Valor da Inscrição:            " + jTextFieldValor.getText() + "\n\n");
        // jTextArea.setText(jTextArea.getText()+"Classe:     "+jTextFieldClasse.getText()+"\n\n");

        jTextArea.setText(jTextArea.getText() + " *Obrigado por fazeres de nós a tua preferência."
                + "Volte Sempre*\n\n\n");
        
        
        jTextArea.setText(jTextArea.getText() + "                          Assinatura "
                + "\n\n\n");
          jTextArea.setText(jTextArea.getText() + "========================================================= \n\n\n");

    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pesquisar_aluno();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        conexao = ModuloConexao.conector();

        try {
            String sql = ("Select nome,nif,endereco ,telefone, email from tbempresa ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            while (rs.next()) {
                nome = rs.getString("nome");
                nif = rs.getString("nif");
                endereco = rs.getString("endereco");
                fone = rs.getString("telefone");
                email = rs.getString("email");
                //jTextArea.setText(String.valueOf(nome));
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro ao Consultar Totais!\nERRO" + error);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
         jTextFieldID.setText(null);
                    jTextFieldNome.setText(null);
                    jTextFieldClasse.setText(null);
                    jTextFieldTurno.setText(null);
                    jTextFieldTurma.setText(null);
                    jTextFieldTurma1.setText(null);
                    jTextFieldSala.setText(null);
                    jTextFieldSala1.setText(null);
                    jTextFieldValor.setText(null) ;
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprActionPerformed
        try {
            // TODO add your handling code here:
            jTextArea.print();
        } catch (PrinterException ex) {
           // JOptionPane.showMessageDialog(null,"Erro ao imprmir");
        }
    }//GEN-LAST:event_jButtonImprActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JButton jButtonImpr;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldClasse;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSala;
    private javax.swing.JTextField jTextFieldSala1;
    private javax.swing.JTextField jTextFieldTurma;
    private javax.swing.JTextField jTextFieldTurma1;
    private javax.swing.JTextField jTextFieldTurno;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
