/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jelson Fernandes
 */
public class ImprimirParcela extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String nome, nif, endereco, fone, email;

    /**
     * Creates new form ImprimirCadastro
     *
     * @param Pag
     * @param idPag
     *
     */
    public ImprimirParcela(int Pag) {
        initComponents();
        conexao = ModuloConexao.conector();

        String sql = "select*from tbpagamentos where id_pagamento =" + Pag;
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.first()) {

                
                jTextFieldIDPag.setText(String.valueOf(Pag));
                jTextFieldNome.setText(rs.getString(2));
                Classe.setText(rs.getString(3));
                jTextFieldServico.setText(rs.getString(4));
                jTextFieldValor.setText(rs.getString(5) + " KZ ");
                jTextFieldIDContrato.setText(rs.getString(6));

                
            } else {
                JOptionPane.showMessageDialog(null, "Pagamento não Encontrado");
            }

        } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e) {
            JOptionPane.showMessageDialog(null, "Nº de Pagamento Inválido");
            // System.out.println(e);
        } catch (HeadlessException | SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        }

    }

    private void pesquisar_Pagamentos() {

        try {

            // a linha abaixo cria uma caixa de entrada do tipo JOption Pane
            String Pagamento = JOptionPane.showInputDialog("Número de Pagamento");
            String sql = "select*from tbpagamentos where id_pagamento =" + Pagamento;
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            try {
                pst = conexao.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {

                    // File file = archivo.getSelectedFile();
                    jTextFieldIDPag.setText(rs.getString(1));
                    jTextFieldNome.setText(rs.getString(2));
                    Classe.setText(rs.getString(3));
                    jTextFieldServico.setText(rs.getString(4));
                    jTextFieldValor.setText(rs.getString(5) + " KZ ");
                    jTextFieldIDContrato.setText(rs.getString(6));

                    // txtAluPesquisar.setEnabled(false);
                    //  tblContrato.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Pagamento não Encontrado");
                }

            } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException e) {
                JOptionPane.showMessageDialog(null, "Nº de Pagamento Inválido");
                // System.out.println(e);
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, e2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ImprimirParcela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        Classe = new javax.swing.JTextField();
        jTextFieldServico = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonGerar = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonImpr = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldIDPag = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIDContrato = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Classe");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Seviço");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Valor");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNome.setEnabled(false);

        Classe.setEnabled(false);

        jTextFieldServico.setEnabled(false);

        jTextFieldValor.setEnabled(false);

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea);

        jButtonGerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGerar.setText("GERAR FACTURA");
        jButtonGerar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReset.setText("RESET");
        jButtonReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonImpr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonImpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/blueprinter.png"))); // NOI18N
        jButtonImpr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/search.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldIDPag.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nº");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldIDContrato.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jButtonImpr, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIDPag, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIDContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                        .addGap(95, 95, 95)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Classe)
                            .addComponent(jTextFieldNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldServico, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addGap(137, 137, 137)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIDContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIDPag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Classe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldServico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonImpr, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        // TODO add your handling code here:

        // String dataSistema = String.valueOf(nome);
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        jTextArea.setText(formatador.format(data));
        jTextArea.setText(jTextArea.getText() + "\n" + data + "\n\n");

        jTextArea.setText(jTextArea.getText() + "===============RECIBO DE CADASTRO DO ALUNO===============   \n\n\n");
        jTextArea.setText(jTextArea.getText() + "EMPRESA:   " + nome + "\n");
        jTextArea.setText(jTextArea.getText() + "NIF:       " + nif + "\n");
        jTextArea.setText(jTextArea.getText() + "ENDEREÇO:  " + endereco + "\n");
        jTextArea.setText(jTextArea.getText() + "EMAIL:     " + email + "\n");
        jTextArea.setText(jTextArea.getText() + "TELEFONE:  " + fone + "\n\n");
        jTextArea.setText(jTextArea.getText() + "=========================================================  \n\n\n");
        jTextArea.setText(jTextArea.getText() + "Nome:                       " + jTextFieldNome.getText() + "\n\n");
        jTextArea.setText(jTextArea.getText() + "Classe:                     " + Classe.getText() + "\n\n");

        jTextArea.setText(jTextArea.getText() + "Tipo de Serviço:            " + jTextFieldServico.getText() + "\n\n");

        jTextArea.setText(jTextArea.getText() + "Valor:                      " + jTextFieldValor.getText() + "\n\n");

        // jTextArea.setText(jTextArea.getText()+"Classe:     "+jTextFieldClasse.getText()+"\n\n");
        jTextArea.setText(jTextArea.getText() + " *Obrigado por fazeres de nós a tua preferência."
                + "Volte Sempre*\n\n\n");

        jTextArea.setText(jTextArea.getText() + "                          Assinatura "
                + "\n\n\n");
        jTextArea.setText(jTextArea.getText() + "========================================================= \n\n\n");

    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pesquisar_Pagamentos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        conexao = ModuloConexao.conector();

        try {
            String sql = ("Select nome,nif,endereco ,telefone, email from tbempresa ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            while (rs.next()) {
                nome = rs.getString("nome");
                nif = rs.getString("nif");
                endereco = rs.getString("endereco");
                fone = rs.getString("telefone");
                email = rs.getString("email");
                //jTextArea.setText(String.valueOf(nome));
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro ao Consultar Totais!\nERRO" + error);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldIDContrato.setText(null);
        jTextFieldNome.setText(null);
        Classe.setText(null);
        jTextFieldServico.setText(null);
        jTextFieldValor.setText(null);

        jTextFieldIDContrato.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprActionPerformed
        try {
            // TODO add your handling code here:
            jTextArea.print();
        } catch (PrinterException ex) {
            // JOptionPane.showMessageDialog(null,"Erro ao imprmir");
        }
    }//GEN-LAST:event_jButtonImprActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Classe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JButton jButtonImpr;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldIDContrato;
    private javax.swing.JTextField jTextFieldIDPag;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldServico;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
