/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import java.sql.*;

import br.com.mtsoftware.dal.ModuloConexao;
import br.com.mtsoftware.dal.ModuloConexao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jelson Fernandes
 */
public class ParcelasCotrato extends javax.swing.JInternalFrame {

    Connection conexao = null;
    //criando variaveis especiais para conexão com o banco
    //prepared statement e resultSet são frameworks do pacote java.sql
    //e servem para preparar eexecutar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    int qtdParcela;
    int i = 1, cont = 1;;
    float valor, Total, porc, valorParcela;
   
    ModeloParcelaContrato mod = new ModeloParcelaContrato();
    ControleParcelamentoContrato control = new ControleParcelamentoContrato();

    /**
     * Creates new form ParcelasCotrato
     */
    public ParcelasCotrato(int cod) {
        try {
            initComponents();
             Data.setText(new SimpleDateFormat("dd-MM-yyyy").format(new java.util.Date(System.currentTimeMillis())));
            conexao = ModuloConexao.conector();
            String sql=("select*from tbacontratos where id_contrato="+cod);
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            Contrato.setText(String.valueOf(cod));
            ValorContrato.setText(String.valueOf(rs.getFloat("valor")));
            QuantidadesDeParcelas.setText(String.valueOf(rs.getInt("nparcelas")));
        } catch (SQLException ex) {
            Logger.getLogger(ParcelasCotrato.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

   

    private void pesquisar_contrato() {

        String sql = "select id_contrato as ID,nome as Nome, valor as Valor,vencipriparce as Vencimento,nparcelas as Parcelas   from tbacontratos where nome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, contratopesqusar.getText() + "%");
            rs = pst.executeQuery();
            tblConParc.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Buscar o contrato!\nERRO:" + e);
        }

    }

    private void setar_campos() {
        int setar = tblConParc.getSelectedRow();
        Contrato.setText(tblConParc.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tblConParc.getModel().getValueAt(setar, 1).toString());
        ValorContrato.setText(tblConParc.getModel().getValueAt(setar, 2).toString());
        Data.setText(tblConParc.getModel().getValueAt(setar, 3).toString());
        QuantidadesDeParcelas.setText(tblConParc.getModel().getValueAt(setar, 4).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Contrato = new javax.swing.JTextField();
        ValorContrato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnParcelas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ValorTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        QuantidadesDeParcelas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Juro = new javax.swing.JTextField();
        Data = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        contratopesqusar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblConParc = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Parcelas do Cotrato");
        setPreferredSize(new java.awt.Dimension(807, 680));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID Contrato");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Contrato.setBackground(new java.awt.Color(102, 255, 255));
        Contrato.setForeground(new java.awt.Color(255, 51, 153));
        Contrato.setEnabled(false);

        ValorContrato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ValorContrato.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Valor do contrato");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data da 1ª Parcela");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnParcelas.setBackground(new java.awt.Color(255, 255, 255));
        btnParcelas.setText("Parcelar");
        btnParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Valor do Total");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ValorTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ValorTotal.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Nº de Parcelas");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        QuantidadesDeParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        QuantidadesDeParcelas.setEnabled(false);
        QuantidadesDeParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadesDeParcelasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("       Juro");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Juro.setText("  00");
        Juro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Juro.setEnabled(false);

        Data.setEnabled(false);
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(0, 255, 255));
        Tabela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabela.setForeground(new java.awt.Color(102, 102, 255));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TabelaVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        txtNome.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contrato, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(431, 431, 431)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Data)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValorContrato)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuantidadesDeParcelas))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Juro, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addComponent(btnParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Data))
                                .addGap(5, 5, 5)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(QuantidadesDeParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Juro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ValorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contratopesqusar.setBackground(new java.awt.Color(255, 255, 204));
        contratopesqusar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contratopesqusarKeyReleased(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/Pesquisar (2).png"))); // NOI18N
        jLabel13.setText("     ");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblConParc.setBackground(new java.awt.Color(255, 255, 204));
        tblConParc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblConParc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConParcMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblConParc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(contratopesqusar, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contratopesqusar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelasActionPerformed
        // TODO add your handling code here:

        qtdParcela = Integer.parseInt(QuantidadesDeParcelas.getText());
        valor = Float.parseFloat(ValorContrato.getText());
        porc = Float.parseFloat(Juro.getText());
        valorParcela = valor / qtdParcela;
       // Tabela.removeAll();
        preecherTabela();
    }//GEN-LAST:event_btnParcelasActionPerformed
    public class ModeloTabela extends AbstractTableModel {

        private ArrayList linhas = null;
        private String[] colunas = null;

        public ModeloTabela(ArrayList lin, String[] col) {
            setLinhas(lin);
            setColunas(col);

        }

        public ArrayList getLinhas() {
            return linhas;
        }

        public void setLinhas(ArrayList dados) {
            linhas = dados;
        }

        public String[] getColunas() {
            return colunas;
        }

        public void setColunas(String[] nomes) {
            colunas = nomes;
        }

        public int getColumnCount() {
            return colunas.length;
        }

        public int getRowCount() {
            return linhas.size();
        }

        public String getColumnName(int numCol) {
            return colunas[numCol];
        }

        public Object getValueAt(int numLin, int numCol) {
            Object[] linha = (Object[]) getLinhas().get(numLin);
            return linha[numCol];
        }
    }

    //  Você está retornando o 'toString' dos elementos da sua lista 
//Faça assim: 

    private void contratopesqusarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contratopesqusarKeyReleased
        // chamando o método pesquisar campos
        pesquisar_contrato();
    }//GEN-LAST:event_contratopesqusarKeyReleased

    private void QuantidadesDeParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadesDeParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadesDeParcelasActionPerformed

    private void tblConParcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConParcMouseClicked
        // TODO add your handling code here:
        setar_campos();
    }//GEN-LAST:event_tblConParcMouseClicked

    private void TabelaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TabelaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaVetoableChange

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
// Método para Salvar parcelas no banco
        int j = 1;
        //jfAjustaData parcelas=new AjustaData();
        String datavenc= Data.getText();
        String dia, mes, ano;// Variavel para armazenar data
        dia = "" + datavenc.charAt(0) + datavenc.charAt(1) + "-";
        mes = "" + datavenc.charAt(3) + datavenc.charAt(4);
        ano = "-" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9);
        int anoInt = Integer.parseInt("" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (j < cont) {

            if (mesInt < 10) {
                
                try {
                    mod.setId_contrato(Integer.parseInt(Contrato.getText()));
                    mod.setValorparc(valorParcela + (valorParcela * (porc / 100)));
                    mod.setValor_total(Float.parseFloat(ValorTotal.getText()));
                    mod.setValor_contrato(Float.parseFloat(ValorContrato.getText()));
                    mod.setNumero_parcela(j);
                    mod.setData_venc(dia + "0" + mesInt + "-" + anoInt);
                    control.SalvarParcela(mod);
                } catch (SQLException ex) {
                    Logger.getLogger(ParcelasCotrato.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
                   
                    
                    
                   
              
                

            } else {
                
               
                try {
                    mod.setId_contrato(Integer.parseInt(Contrato.getText()));
                    mod.setValorparc(valorParcela + (valorParcela * (porc / 100)));
                    mod.setValor_total(Float.parseFloat(ValorTotal.getText()));
                    mod.setValor_contrato(Float.parseFloat(ValorContrato.getText()));
                    mod.setNumero_parcela(j);
                    mod.setData_venc(dia + "0" + mesInt + "-" + anoInt);
                
                    control.SalvarParcela(mod);
                    
                    
                    
                    
                  
                    // dados.add(new Object[]{i, dia + (Integer.parseInt(mes) + i) + ano, Valoratu});
                    
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ParcelasCotrato.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
             mesInt++;
            if (mesInt > 12) {
                anoInt++;

                mesInt = 1;
                    }
             
           j++;


    }//GEN-LAST:event_btnSalvarActionPerformed
    JOptionPane.showMessageDialog(rootPane, "Parcelas Salvas com Sucesso!");

    
    }
    
    
    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataActionPerformed
        
    

    public void preecherTabela() {

        //outro
        
        ArrayList dados = new ArrayList();
        
        //jfAjustaData parcelas=new AjustaData();
        String[] Colunas = new String[]{"Nº da Parcela", "Data de Vencimento", "Valor da Parcela"};
        float Valoratu, Total = 0;
        String data = Data.getText();
        
        String dia, mes, ano;
        
        dia = "" + data.charAt(0) + data.charAt(1) + "-";
        mes = "" + data.charAt(3) + data.charAt(4);
        ano = "-" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9);
        Valoratu = valorParcela + (valorParcela * (porc / 100));
        int anoInt = Integer.parseInt("" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (i <= qtdParcela) {
            Total = Total + Valoratu;
           
            
    

            if (mesInt < 10) {

                dados.add(new Object[]{i, "0" + dia + mesInt + "-" + anoInt, Valoratu});
            } else {

                dados.add(new Object[]{i, dia + mesInt + "-" + anoInt, Valoratu});

            }
            mesInt++;
            if (mesInt > 12) {
                anoInt++;

                mesInt = 1;
                
 
            }
             
            // dados.add(new Object[]{i, dia + (Integer.parseInt(mes) + i) + ano, Valoratu});
            i++;
            cont++;
//            if(mesInt==1){
//                  mesInt=Integer.parseInt("Janeiro");
//               }else if(mesInt==2){
//                    mesInt=Integer.parseInt("Fevereiro");
//               }else if(mesInt==3){
//                    mesInt=Integer.parseInt("Março");
//               }else if(mesInt==4){
//                    mesInt=Integer.parseInt("Abril");
//               }else if(mesInt==5){
//                    mesInt=Integer.parseInt("Maio");
//               }else if(mesInt==6){
//                    mesInt=Integer.parseInt("Junho");
//               }else if(mesInt==7){
//                    mesInt=Integer.parseInt("Julho");
//               }else if(mesInt==8){
//                    mesInt=Integer.parseInt("Agosto");
//               }else if(mesInt==9){
//                    mesInt=Integer.parseInt("Setembro");
//               }else if(mesInt==10){
//                    mesInt=Integer.parseInt("Outubro");
//               }else if(mesInt==11){
//                    mesInt=Integer.parseInt("Novembro");
//               }else if(mesInt==12){
//                    mesInt=Integer.parseInt("Dezembro");
//               }
        }
        
        ValorTotal.setText(String.valueOf(Total));

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        
        Tabela.setModel((TableModel) modelo);

        Tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
        Tabela.getColumnModel().getColumn(0).setResizable(false);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(230);
        Tabela.getColumnModel().getColumn(1).setResizable(false);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(230);
        Tabela.getColumnModel().getColumn(2).setResizable(false);
        //Reorganizando o cabeçalho 
        Tabela.getTableHeader().setReorderingAllowed(false);

        Tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrato;
    private javax.swing.JTextField Data;
    private javax.swing.JTextField Juro;
    private javax.swing.JTextField QuantidadesDeParcelas;
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField ValorContrato;
    private javax.swing.JTextField ValorTotal;
    private javax.swing.JButton btnParcelas;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField contratopesqusar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblConParc;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
