/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jelson Fernandes
 */
public class ParcelaVendas extends javax.swing.JInternalFrame {
    Connection conexao = null;
    //criando variaveis especiais para conexão com o banco
    //prepared statement e resultSet são frameworks do pacote java.sql
    //e servem para preparar eexecutar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    int  qtdParcela;
     int i = 1, cont = 1;
    float valorParcela, valor,porc,juro;
    ModeloParcelaVenda mod = new ModeloParcelaVenda();
    ControleParcelamentoVenda control = new ControleParcelamentoVenda();

    /**
     * Creates new form ParcelaVendas
     */
    public ParcelaVendas(int cod) {
        try {
            initComponents();
            getContentPane().setBackground(Color.yellow);
             jTextFieldData.setText(new SimpleDateFormat("dd-MM-yyyy").format(new java.util.Date(System.currentTimeMillis())));
            conexao = ModuloConexao.conector();
            String sql=("select*from tbvendas where id_venda="+cod);
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            jTextFieldCod.setText(String.valueOf(cod));
            jTextFieldVenda.setText(String.valueOf(rs.getFloat("valor_venda")));
//            jTextFieldData.setText(String.valueOf(rs.getDate("data_venda")));
        } catch (SQLException ex) {
            Logger.getLogger(ParcelaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ParcelaVendas() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQunt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldJuro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ValorTotal = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonParcelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CODIGO");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCod.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Valor da Venda");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldVenda.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Data");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldData.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quantidade de Parcelas");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldQunt.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Número da Parcela");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNum.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Juro");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldJuro.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("             Valor Total");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ValorTotal.setBackground(new java.awt.Color(255, 255, 204));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonParcelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonParcelar.setText("Parcelar");
        jButtonParcelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonParcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("Gerar Duplicatas");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))
                                    .addComponent(jTextFieldCod))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldVenda)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonParcelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(312, 312, 312))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(jTextFieldQunt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNum, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addGap(138, 138, 138)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addGap(86, 86, 86))
                                    .addComponent(jTextFieldJuro))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ValorTotal)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addGap(66, 66, 66))
                                    .addComponent(jTextFieldData))))
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonParcelar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldJuro, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(ValorTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQunt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("                                      GERAR PARCELAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonParcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcelarActionPerformed
        // TODO add your handling code here:
         qtdParcela= Integer.parseInt(jTextFieldQunt.getText());
        valor = Float.parseFloat(jTextFieldVenda.getText());
        porc = Float.parseFloat(jTextFieldJuro.getText());
        valorParcela = valor / qtdParcela;
         preecherTabela();
    }//GEN-LAST:event_jButtonParcelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
       // Método para Salvar parcelas no banco
        int j = 1;
        //jfAjustaData parcelas=new AjustaData();
        String datavenc= jTextFieldData.getText();
        String dia, mes, ano;// Variavel para armazenar data
        dia = "" + datavenc.charAt(0) + datavenc.charAt(1) + "-";
        mes = "" + datavenc.charAt(3) + datavenc.charAt(4);
        ano = "-" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9);
        int anoInt = Integer.parseInt("" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (j < cont) {

            if (mesInt < 10) {
                
                try {
                    mod.setId_Venda(Integer.parseInt(jTextFieldCod.getText()));
                    mod.setValorparc(valorParcela + (valorParcela * (porc / 100)));
                    mod.setValor_total(Float.parseFloat(ValorTotal.getText()));
                    mod.setValor_Venda(Float.parseFloat(jTextFieldVenda.getText()));
                    mod.setNumero_parcela(j);
                    mod.setData_venc(dia + "0" + mesInt + "-" + anoInt);
                    control.SalvarParcela(mod);
                } catch (SQLException ex) {
                    Logger.getLogger(ParcelasCotrato.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
                   
                    
                    
                   
              
                

            } else {
                
               
                try {
                    mod.setId_Venda(Integer.parseInt(jTextFieldCod.getText()));
                    mod.setValorparc(valorParcela + (valorParcela * (porc / 100)));
                    mod.setValor_total(Float.parseFloat(ValorTotal.getText()));
                    mod.setValor_Venda(Float.parseFloat(jTextFieldVenda.getText()));
                    mod.setNumero_parcela(j);
                    mod.setData_venc(dia + "0" + mesInt + "-" + anoInt);
                
                    control.SalvarParcela(mod);
                    
                    
                    
                    
                  
                    // dados.add(new Object[]{i, dia + (Integer.parseInt(mes) + i) + ano, Valoratu});
                    
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ParcelasCotrato.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
             mesInt++;
            if (mesInt > 12) {
                anoInt++;

                mesInt = 1;
                    }
             
           j++;


    }                                         
    JOptionPane.showMessageDialog(rootPane, "Parcelas Salvas com Sucesso!");

    
    
    }//GEN-LAST:event_btnSalvarActionPerformed

    
     public class ModeloTabela extends AbstractTableModel {

        private ArrayList linhas = null;
        private String[] colunas = null;

        public ModeloTabela(ArrayList lin, String[] col) {
            setLinhas(lin);
            setColunas(col);

        }

        public ArrayList getLinhas() {
            return linhas;
        }

        public void setLinhas(ArrayList dados) {
            linhas = dados;
        }

        public String[] getColunas() {
            return colunas;
        }

        public void setColunas(String[] nomes) {
            colunas = nomes;
        }

        public int getColumnCount() {
            return colunas.length;
        }

        public int getRowCount() {
            return linhas.size();
        }

        public String getColumnName(int numCol) {
            return colunas[numCol];
        }

        public Object getValueAt(int numLin, int numCol) {
            Object[] linha = (Object[]) getLinhas().get(numLin);
            return linha[numCol];
        }
    }

    //  Você está retornando o 'toString' dos elementos da sua lista 
//Faça assim: 

    private void contratopesqusarKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // chamando o método pesquisar campos
//        pesquisar_contrato();
    }                                            

    private void QuantidadesDeParcelasActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void tblConParcMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
//        setar_campos();
    }                                       

    private void TabelaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {                                      
        // TODO add your handling code here:
    }                                     

    
        

    
    
    private void DataActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    
        
    

    public void preecherTabela() {

        //outro
        
        ArrayList dados = new ArrayList();
        
        //jfAjustaData parcelas=new AjustaData();
        String[] Colunas = new String[]{"Nº da Parcela", "Data de Vencimento", "Valor da Parcela"};
        float Valoratu, Total = 0;
        String data = jTextFieldData.getText();
        
        String dia, mes, ano;
        
        dia = "" + data.charAt(0) + data.charAt(1) + "-";
        mes = "" + data.charAt(3) + data.charAt(4);
        ano = "-" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9);
        Valoratu = valorParcela + (valorParcela * (porc / 100));
        int anoInt = Integer.parseInt("" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (i <= qtdParcela) {
            Total = Total + Valoratu;
           
            
    

            if (mesInt < 10) {

                dados.add(new Object[]{i, "0" + dia + mesInt + "-" + anoInt, Valoratu});
            } else {

                dados.add(new Object[]{i, dia + mesInt + "-" + anoInt, Valoratu});

            }
            mesInt++;
            if (mesInt > 12) {
                anoInt++;

                mesInt = 1;
                
 
            }
             
            // dados.add(new Object[]{i, dia + (Integer.parseInt(mes) + i) + ano, Valoratu});
            i++;
            cont++;
//            if(mesInt==1){
//                  mesInt=Integer.parseInt("Janeiro");
//               }else if(mesInt==2){
//                    mesInt=Integer.parseInt("Fevereiro");
//               }else if(mesInt==3){
//                    mesInt=Integer.parseInt("Março");
//               }else if(mesInt==4){
//                    mesInt=Integer.parseInt("Abril");
//               }else if(mesInt==5){
//                    mesInt=Integer.parseInt("Maio");
//               }else if(mesInt==6){
//                    mesInt=Integer.parseInt("Junho");
//               }else if(mesInt==7){
//                    mesInt=Integer.parseInt("Julho");
//               }else if(mesInt==8){
//                    mesInt=Integer.parseInt("Agosto");
//               }else if(mesInt==9){
//                    mesInt=Integer.parseInt("Setembro");
//               }else if(mesInt==10){
//                    mesInt=Integer.parseInt("Outubro");
//               }else if(mesInt==11){
//                    mesInt=Integer.parseInt("Novembro");
//               }else if(mesInt==12){
//                    mesInt=Integer.parseInt("Dezembro");
//               }
        }
        
        ValorTotal.setText(String.valueOf(Total));

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        
        Tabela.setModel((TableModel) modelo);

        Tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
        Tabela.getColumnModel().getColumn(0).setResizable(false);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(350);
        Tabela.getColumnModel().getColumn(1).setResizable(false);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(350);
        Tabela.getColumnModel().getColumn(2).setResizable(false);
        //Reorganizando o cabeçalho 
        Tabela.getTableHeader().setReorderingAllowed(false);

        Tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JTextField ValorTotal;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonParcelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldJuro;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldQunt;
    private javax.swing.JTextField jTextFieldVenda;
    // End of variables declaration//GEN-END:variables
}
