/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jelson Fernandes
 */
public class PesquisarReceitas extends javax.swing.JInternalFrame {

    Connection conexao = null;
    //criando variaveis especiais para conexão com o banco
    //prepared statement e resultSet são frameworks do pacote java.sql
    //e servem para preparar eexecutar as instruções SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    String vencimento;
    int diaVenc, mesVenc, anoVenc;
    int valida;
    String Class=null;

    /**
     * Creates new form PesquisarReceitas
     */
    public PesquisarReceitas() {
        initComponents();
         getContentPane().setBackground(Color.white);
    }
    private void somatabela(){
          Double orcamento = 0.0;
for (int i = 0; i < jTableRecetas.getRowCount(); i++) {
    orcamento += Double.parseDouble((String) jTableRecetas.getValueAt(i, 1));
//   float convert=(float) Double.parseDouble(jTextFieldValorTotal.getText());
jTextFieldValorTotal.setText(String.valueOf(orcamento) + " AKZ");
}
        
    }
    

          public Component getTableCellRendererComponent(JTable tabela,Object value,boolean isSelected,boolean hasFocus,int row,int column){
             {
                 
             }
        return null;
          
      } 
    public void preencherTabela(String sql) {
        conexao = ModuloConexao.conector();
        // conexao = ModuloConexao.conector();
        
        //outro
        ArrayList dados = new ArrayList();
        //jfAjustaData parcelas=new AjustaData();

        String[] Colunas = new String[]{"ID", "Valor","Tipo","Descrição","Usuário","Més","Ano"};
        //
 




        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.first();
            do {
                dados.add(new Object[]{rs.getString("id_recedesp"), rs.getString("valor"), rs.getString("tipo"), rs.getString("descricao"), rs.getString("usuario"), rs.getString("mes"), rs.getString("ano")});
            } while (rs.next());

            // String foundType = rs.getString(1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!|nERRO:" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableRecetas.setModel((TableModel) modelo);
        jTableRecetas.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableRecetas.getColumnModel().getColumn(0).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableRecetas.getColumnModel().getColumn(1).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableRecetas.getColumnModel().getColumn(2).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableRecetas.getColumnModel().getColumn(3).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTableRecetas.getColumnModel().getColumn(4).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableRecetas.getColumnModel().getColumn(5).setResizable(false);
        jTableRecetas.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTableRecetas.getColumnModel().getColumn(5).setResizable(false);
        

        //Reorganizando o cabeçalho 
        jTableRecetas.getTableHeader().setReorderingAllowed(false);
        jTableRecetas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableRecetas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
  

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRecetas = new javax.swing.JTable();
        jTextFieldMés = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableRecetas.setBackground(new java.awt.Color(255, 51, 0));
        jTableRecetas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableRecetas.setForeground(new java.awt.Color(255, 255, 0));
        jTableRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableRecetas);

        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       Insira o Ano");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("       Insira o més");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo ");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".....", "Receita", "Despesa" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Total");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldValorTotal.setBackground(new java.awt.Color(255, 255, 102));
        jTextFieldValorTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldValorTotal.setForeground(new java.awt.Color(0, 204, 0));
        jTextFieldValorTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldValorTotal.setDisabledTextColor(new java.awt.Color(0, 204, 51));
        jTextFieldValorTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMés, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAno, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipo, 0, 122, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addGap(445, 445, 445)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMés, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("  RELATÓRIO DE RECEITAS & DESPESAS MENSAL");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//select*from tbrece_despes where year (data_recdesp)='"+ jTextFieldAno.getText()+"
//        preencherTabela("select*from tbrece_despes  where year (data_recdesp)='" + jTextFieldAno.getText()+"and  where month(data_recdesp)="+jTextFieldMés.getText()+"and where(tipo)="+jComboBoxTipo.getSelectedItem()+"'");
        
         preencherTabela("select id_recedesp,valor,tipo,descricao,usuario,month (data_recdesp)as mes,year (data_recdesp) as ano from tbrece_despes where  month (data_recdesp)='"+jTextFieldMés.getText()+"'"+"and year (data_recdesp)='"+ jTextFieldAno.getText()+"'"+"and  (tipo)='"+ jComboBoxTipo.getSelectedItem()+"'");
         
         
         somatabela();
         
         
         
         
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRecetas;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldMés;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
