/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mtsoftware.telas;

import br.com.mtsoftware.dal.ModuloConexao;
import static br.com.mtsoftware.telas.TelaPrincipal.BoletimConsulta;
import static br.com.mtsoftware.telas.TelaPrincipal.Desktop;
import java.awt.Color;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import java.awt.Graphics;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Jelson Fernandes
 */
public class TelaPrincipal extends javax.swing.JFrame {
Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
   
        getContentPane().setBackground(new Color(255,255,240));
        initComponents();
        
        setIcon();
         conexao = ModuloConexao.conector();
        
        
        // ImageIcon icone=new ImageIcon("/br/com/mtsoftware/icones/bdon.png");
        //setIconImage(icone.getImage());
        

        Desktop.setBackground(Color.pink);
//        this.setExtendedState(this.getExtendedState() | TelaPrincipal.MAXIMIZED_BOTH);
        ActualizadorHora.start(jLabelHorario);
       
        
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        ImageIcon icone= new ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/Schoolsystem.jpg"));
        Image image = icone.getImage();
        Desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabelLicenca = new javax.swing.JLabel();
        jLabelEspiracao = new javax.swing.JLabel();
        jButtonLicenca = new javax.swing.JButton();
        lblUsuario = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabelempresa = new javax.swing.JLabel();
        jLabelNLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNif = new javax.swing.JLabel();
        jLabelend = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        lblData = new java.awt.Label();
        Menu1 = new javax.swing.JMenuBar();
        menCadEmpr = new javax.swing.JMenu();
        menCadEmpre = new javax.swing.JMenuItem();
        menFuncionarios = new javax.swing.JMenuItem();
        USUARIO = new javax.swing.JMenu();
        menCadUsu = new javax.swing.JMenuItem();
        jMenuItemProgramador = new javax.swing.JMenuItem();
        jMenuItemValidacao = new javax.swing.JMenuItem();
        jMenuItemCadLicence = new javax.swing.JMenuItem();
        Escola = new javax.swing.JMenu();
        menCadastro = new javax.swing.JMenuItem();
        menContratos = new javax.swing.JMenuItem();
        menClasses = new javax.swing.JMenuItem();
        jMenuBoletim = new javax.swing.JMenuItem();
        BoletimConsulta = new javax.swing.JMenuItem();
        jMenuItemMensaldade = new javax.swing.JMenuItem();
        menPagamentos = new javax.swing.JMenuItem();
        jMenuItemTurnos = new javax.swing.JMenuItem();
        jMenuItemCadNotas = new javax.swing.JMenuItem();
        nenCadCli = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        COMERCIAL1 = new javax.swing.JMenu();
        jMenuItemCadProdutos = new javax.swing.JMenuItem();
        jMenuItemVenda = new javax.swing.JMenuItem();
        menCadOs = new javax.swing.JMenuItem();
        jMenuItemBaixaVenda = new javax.swing.JMenuItem();
        jMenuItemPesquiVendas = new javax.swing.JMenuItem();
        jMenuItemFinancas = new javax.swing.JMenuItem();
        MenAju = new javax.swing.JMenu();
        MenAjuSob1 = new javax.swing.JMenuItem();
        MenRel = new javax.swing.JMenu();
        MenRelServ1 = new javax.swing.JMenuItem();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jMenuItemFuncionários = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenOpc = new javax.swing.JMenu();
        MenOpcSai1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Desktop.setForeground(new java.awt.Color(255, 51, 204));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 255, 204));
        jButton1.setText("GOOGLE");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelLicenca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLicenca.setText("         Licença");
        jLabelLicenca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEspiracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEspiracao.setForeground(new java.awt.Color(51, 0, 255));
        jLabelEspiracao.setText("         Licença");
        jLabelEspiracao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonLicenca.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLicenca.setForeground(new java.awt.Color(0, 0, 204));
        jButtonLicenca.setText("Clica Para Obter a Tua Licença     ");
        jButtonLicenca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLicencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118)
                .addComponent(jLabelLicenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEspiracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87)
                .addComponent(jButtonLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabelEspiracao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLicenca))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("USUÁRIO:");

        jLabel1.setFont(new java.awt.Font("Olympus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("TOKES MULTISOFT");

        jlabelempresa.setBackground(new java.awt.Color(255, 255, 255));
        jlabelempresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabelempresa.setForeground(new java.awt.Color(0, 51, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/LOGSOFT_Small-3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("NIF:");

        jLabelNif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelend.setForeground(new java.awt.Color(255, 51, 0));
        jLabelend.setText("                  ENDEREÇO");

        jLabelHorario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHorario.setForeground(new java.awt.Color(255, 0, 51));
        jLabelHorario.setText("               Horário");

        lblData.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 51, 153));
        lblData.setText("Data");

        Menu1.setBackground(new java.awt.Color(255, 0, 0));
        Menu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menCadEmpr.setBorder(new javax.swing.border.MatteBorder(null));
        menCadEmpr.setForeground(new java.awt.Color(51, 153, 255));
        menCadEmpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/house.png"))); // NOI18N
        menCadEmpr.setText("EMPRESA");
        menCadEmpr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menCadEmpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadEmprActionPerformed(evt);
            }
        });

        menCadEmpre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menCadEmpre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menCadEmpre.setForeground(new java.awt.Color(51, 51, 255));
        menCadEmpre.setText("Cadastro da Empresa");
        menCadEmpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadEmpreActionPerformed(evt);
            }
        });
        menCadEmpr.add(menCadEmpre);

        menFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menFuncionarios.setForeground(new java.awt.Color(51, 51, 255));
        menFuncionarios.setText("Funcionários");
        menFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFuncionariosActionPerformed(evt);
            }
        });
        menCadEmpr.add(menFuncionarios);

        Menu1.add(menCadEmpr);

        USUARIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        USUARIO.setForeground(new java.awt.Color(0, 204, 255));
        USUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/usuário.png"))); // NOI18N
        USUARIO.setText("USUÁRIO");
        USUARIO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIOActionPerformed(evt);
            }
        });

        menCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menCadUsu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menCadUsu.setForeground(new java.awt.Color(0, 204, 255));
        menCadUsu.setText("Cadastro de Usuários");
        menCadUsu.setEnabled(false);
        menCadUsu.setSelected(true);
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        USUARIO.add(menCadUsu);

        jMenuItemProgramador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProgramador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemProgramador.setForeground(new java.awt.Color(0, 204, 255));
        jMenuItemProgramador.setText("Programador");
        jMenuItemProgramador.setEnabled(false);
        jMenuItemProgramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProgramadorActionPerformed(evt);
            }
        });
        USUARIO.add(jMenuItemProgramador);

        jMenuItemValidacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemValidacao.setForeground(new java.awt.Color(0, 204, 255));
        jMenuItemValidacao.setText("Validação da Senha");
        jMenuItemValidacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemValidacaoActionPerformed(evt);
            }
        });
        USUARIO.add(jMenuItemValidacao);

        jMenuItemCadLicence.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemCadLicence.setForeground(new java.awt.Color(0, 204, 255));
        jMenuItemCadLicence.setText("Cadastro_Licença");
        jMenuItemCadLicence.setEnabled(false);
        jMenuItemCadLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadLicenceActionPerformed(evt);
            }
        });
        USUARIO.add(jMenuItemCadLicence);

        Menu1.add(USUARIO);

        Escola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Escola.setForeground(new java.awt.Color(51, 204, 255));
        Escola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/STUDANT1.png"))); // NOI18N
        Escola.setText("ESCOLA");
        Escola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Escola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolaActionPerformed(evt);
            }
        });

        menCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menCadastro.setBackground(new java.awt.Color(204, 255, 255));
        menCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menCadastro.setForeground(new java.awt.Color(51, 204, 255));
        menCadastro.setText("Cadastro De Alunos");
        menCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroActionPerformed(evt);
            }
        });
        Escola.add(menCadastro);

        menContratos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menContratos.setBackground(new java.awt.Color(255, 255, 255));
        menContratos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menContratos.setForeground(new java.awt.Color(0, 204, 0));
        menContratos.setText("Contratos/Maticulas");
        menContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menContratosActionPerformed(evt);
            }
        });
        Escola.add(menContratos);

        menClasses.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menClasses.setBackground(new java.awt.Color(153, 255, 255));
        menClasses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menClasses.setForeground(new java.awt.Color(51, 204, 255));
        menClasses.setText("Cadastro de Classes");
        menClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClassesActionPerformed(evt);
            }
        });
        Escola.add(menClasses);

        jMenuBoletim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBoletim.setForeground(new java.awt.Color(0, 204, 0));
        jMenuBoletim.setText("Cadastro De Boletim");
        jMenuBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBoletimActionPerformed(evt);
            }
        });
        Escola.add(jMenuBoletim);

        BoletimConsulta.setBackground(new java.awt.Color(255, 255, 255));
        BoletimConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BoletimConsulta.setForeground(new java.awt.Color(51, 204, 255));
        BoletimConsulta.setText("Consulta de Boletim");
        BoletimConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoletimConsultaActionPerformed(evt);
            }
        });
        Escola.add(BoletimConsulta);

        jMenuItemMensaldade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemMensaldade.setForeground(new java.awt.Color(0, 204, 0));
        jMenuItemMensaldade.setText("Efetuar Cobranças");
        jMenuItemMensaldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMensaldadeActionPerformed(evt);
            }
        });
        Escola.add(jMenuItemMensaldade);

        menPagamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menPagamentos.setBackground(new java.awt.Color(255, 255, 255));
        menPagamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menPagamentos.setForeground(new java.awt.Color(51, 204, 255));
        menPagamentos.setText("Controle de Entradas");
        menPagamentos.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        menPagamentos.setEnabled(false);
        menPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPagamentosActionPerformed(evt);
            }
        });
        Escola.add(menPagamentos);

        jMenuItemTurnos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTurnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemTurnos.setForeground(new java.awt.Color(0, 204, 0));
        jMenuItemTurnos.setText("Cadastro de Preços");
        jMenuItemTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurnosActionPerformed(evt);
            }
        });
        Escola.add(jMenuItemTurnos);

        jMenuItemCadNotas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemCadNotas.setForeground(new java.awt.Color(51, 204, 255));
        jMenuItemCadNotas.setText("CADASTRO NOTAS");
        jMenuItemCadNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadNotasActionPerformed(evt);
            }
        });
        Escola.add(jMenuItemCadNotas);

        Menu1.add(Escola);

        nenCadCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nenCadCli.setForeground(new java.awt.Color(51, 0, 255));
        nenCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/clientes.png"))); // NOI18N
        nenCadCli.setText(" CLIENTES");
        nenCadCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nenCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nenCadCliActionPerformed(evt);
            }
        });

        menCadCli.setBackground(new java.awt.Color(255, 255, 255));
        menCadCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menCadCli.setForeground(new java.awt.Color(51, 153, 255));
        menCadCli.setText("Cadastro de Clientes");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        nenCadCli.add(menCadCli);

        jMenuItemFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemFornecedores.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItemFornecedores.setText("Cadastro de Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        nenCadCli.add(jMenuItemFornecedores);

        Menu1.add(nenCadCli);

        COMERCIAL1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        COMERCIAL1.setForeground(new java.awt.Color(0, 102, 51));
        COMERCIAL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/finança.jpg"))); // NOI18N
        COMERCIAL1.setText("FINANÇAS");
        COMERCIAL1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        COMERCIAL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMERCIAL1ActionPerformed(evt);
            }
        });

        jMenuItemCadProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadProdutos.setBackground(new java.awt.Color(0, 102, 51));
        jMenuItemCadProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemCadProdutos.setForeground(new java.awt.Color(0, 102, 51));
        jMenuItemCadProdutos.setText("Cadastro de Produtos");
        jMenuItemCadProdutos.setEnabled(false);
        jMenuItemCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdutosActionPerformed(evt);
            }
        });
        COMERCIAL1.add(jMenuItemCadProdutos);

        jMenuItemVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemVenda.setBackground(new java.awt.Color(0, 102, 51));
        jMenuItemVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemVenda.setForeground(new java.awt.Color(51, 204, 255));
        jMenuItemVenda.setText("VENDA");
        jMenuItemVenda.setEnabled(false);
        jMenuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendaActionPerformed(evt);
            }
        });
        COMERCIAL1.add(jMenuItemVenda);

        menCadOs.setBackground(new java.awt.Color(0, 102, 51));
        menCadOs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menCadOs.setForeground(new java.awt.Color(0, 102, 51));
        menCadOs.setText("Ordem De Serviço");
        menCadOs.setEnabled(false);
        menCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadOsActionPerformed(evt);
            }
        });
        COMERCIAL1.add(menCadOs);

        jMenuItemBaixaVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBaixaVenda.setBackground(new java.awt.Color(0, 102, 51));
        jMenuItemBaixaVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemBaixaVenda.setForeground(new java.awt.Color(51, 0, 255));
        jMenuItemBaixaVenda.setText("Baixar Parcelas");
        jMenuItemBaixaVenda.setEnabled(false);
        jMenuItemBaixaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBaixaVendaActionPerformed(evt);
            }
        });
        COMERCIAL1.add(jMenuItemBaixaVenda);

        jMenuItemPesquiVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPesquiVendas.setBackground(new java.awt.Color(0, 102, 51));
        jMenuItemPesquiVendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemPesquiVendas.setForeground(new java.awt.Color(0, 102, 51));
        jMenuItemPesquiVendas.setText("PESQUISAR VENDA");
        jMenuItemPesquiVendas.setEnabled(false);
        jMenuItemPesquiVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquiVendasActionPerformed(evt);
            }
        });
        COMERCIAL1.add(jMenuItemPesquiVendas);

        jMenuItemFinancas.setBackground(new java.awt.Color(0, 102, 51));
        jMenuItemFinancas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItemFinancas.setForeground(new java.awt.Color(51, 153, 255));
        jMenuItemFinancas.setText("CONTROLE DE FINANÇAS");
        jMenuItemFinancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinancasActionPerformed(evt);
            }
        });
        COMERCIAL1.add(jMenuItemFinancas);

        Menu1.add(COMERCIAL1);

        MenAju.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenAju.setForeground(new java.awt.Color(51, 0, 255));
        MenAju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/ajuda.png"))); // NOI18N
        MenAju.setText("AJUDA");
        MenAju.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MenAjuSob1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        MenAjuSob1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenAjuSob1.setForeground(new java.awt.Color(0, 153, 51));
        MenAjuSob1.setText("Sobre");
        MenAjuSob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSob1ActionPerformed(evt);
            }
        });
        MenAju.add(MenAjuSob1);

        Menu1.add(MenAju);

        MenRel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenRel.setForeground(new java.awt.Color(0, 153, 204));
        MenRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mtsoftware/icones/relatório.png"))); // NOI18N
        MenRel.setText("RELATÓRIOS");
        MenRel.setEnabled(false);
        MenRel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelActionPerformed(evt);
            }
        });

        MenRelServ1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenRelServ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenRelServ1.setForeground(new java.awt.Color(0, 153, 204));
        MenRelServ1.setText("Serviços");
        MenRelServ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelServ1ActionPerformed(evt);
            }
        });
        MenRel.add(MenRelServ1);

        jMenuItemAluno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemAluno.setForeground(new java.awt.Color(0, 153, 204));
        jMenuItemAluno.setText("Alunos");
        jMenuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoActionPerformed(evt);
            }
        });
        MenRel.add(jMenuItemAluno);

        jMenuItemFuncionários.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemFuncionários.setForeground(new java.awt.Color(0, 153, 204));
        jMenuItemFuncionários.setText("Funcionários");
        jMenuItemFuncionários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionáriosActionPerformed(evt);
            }
        });
        MenRel.add(jMenuItemFuncionários);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 153, 204));
        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenRel.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(0, 102, 102));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 153, 204));
        jMenuItem3.setText("Parcelas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenRel.add(jMenuItem3);

        Menu1.add(MenRel);

        MenOpc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenOpc.setForeground(new java.awt.Color(255, 153, 0));
        MenOpc.setText("           OPÇÕES ");
        MenOpc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcActionPerformed(evt);
            }
        });

        MenOpcSai1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenOpcSai1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenOpcSai1.setForeground(new java.awt.Color(255, 255, 0));
        MenOpcSai1.setText("Sair");
        MenOpcSai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSai1ActionPerformed(evt);
            }
        });
        MenOpc.add(MenOpcSai1);
        MenOpc.add(jSeparator1);

        Menu1.add(MenOpc);

        setJMenuBar(Menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabelempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelend, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelNif, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 58, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabelempresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNif, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(jLabelend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadEmpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadEmpreActionPerformed
        // TODO add your handling code here:
        CADASTROEMPRESA empresa = new   CADASTROEMPRESA();
        empresa.setVisible(true);
        Desktop.add(empresa);
         try {
        empresa.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menCadEmpreActionPerformed

    private void menCadEmprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadEmprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadEmprActionPerformed

    private void menCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroActionPerformed

        // método para chamar a tela de alunos
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        Desktop.add(cadastro);
        try {
       cadastro.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menCadastroActionPerformed

    private void menContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menContratosActionPerformed
        try {
            // chamando a tela de contrtos
            
            
            TelaContratos contratos = new TelaContratos();
            
            contratos.setVisible(true);
            Desktop.add(contratos);
             contratos.setMaximum(true); 
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menContratosActionPerformed

    private void menPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPagamentosActionPerformed
        // chamando a tela de pagamentos
        Pagamento pagamentos = new Pagamento();
        pagamentos.setVisible(true);
        Desktop.add(pagamentos);
         try {
       pagamentos.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menPagamentosActionPerformed

    private void menClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClassesActionPerformed
        // TODO add your handling code here:
        ClassesDisciplinas classes = new ClassesDisciplinas();
        classes.setVisible(true);
        Desktop.add(classes);
         try {
       classes.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_menClassesActionPerformed

    private void EscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolaActionPerformed

        
    }//GEN-LAST:event_EscolaActionPerformed

    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        // TODO add your handling code here:
        Clientes clientes = new  Clientes();
        clientes.setVisible(true);
        Desktop.add(clientes);
         try {
   clientes.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menCadCliActionPerformed

    private void nenCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nenCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nenCadCliActionPerformed

    private void MenRelServ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelServ1ActionPerformed
        // TODO add your handling code here:
          int comfirma = JOptionPane.showConfirmDialog(null, "Confirma a Emissão deste Relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
                  if(comfirma==JOptionPane.YES_OPTION){
            try {
                net.sf.jasperreports.engine.JasperPrint print=JasperFillManager.fillReport("lib/report/reportos.jasper",null,conexao);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        
    }//GEN-LAST:event_MenRelServ1ActionPerformed

    private void MenAjuSob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSob1ActionPerformed
        // Chama a tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MenAjuSob1ActionPerformed

    private void MenOpcSai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSai1ActionPerformed
        // TODO add your handling code here:
        // Exibe uma caixa de diálogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenOpcSai1ActionPerformed

    private void MenOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcActionPerformed

    }//GEN-LAST:event_MenOpcActionPerformed

    private void MenRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenRelActionPerformed

    private void COMERCIAL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMERCIAL1ActionPerformed
    try {
        // TODO add your handling code here:
        if(rs.isFirst()){
            JOptionPane.showInputDialog("Esta Área ainda não Está em Funcionamento no momento !"); 
        }
    } catch (SQLException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_COMERCIAL1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
        Date data = new Date();
        DateFormat formatador=DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
         
         conexao = ModuloConexao.conector();

        try {
            String sql = ("Select (nome)as nome from tbempresa ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            while (rs.next()) {
                String nome = rs.getString("nome");
               jlabelempresa.setText(String.valueOf(nome));
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar a Empresa!\nERRO" + error);
        }
        try {
            String sql = ("Select (nif)as nif from tbempresa ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            while (rs.next()) {
                String nif = rs.getString("nif");
              jLabelNif.setText(String.valueOf(nif));
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro ao buscar o Nif!\nERRO" + error);
        }
        try {
            String sql = ("Select (endereco)as Endereco from tbempresa ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            while (rs.next()) {
                String Endereco = rs.getString("Endereco");
               jLabelend.setText(String.valueOf(Endereco));
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro ao buscar o Endereco!\nERRO" + error);
        }
       
        
        try {
            // ImageIcon icone=new ImageIcon("/br/com/mtsoftware/icones/bdon.png");
        //setIconImage(icone.getImage());
        //ImageIcon icone=new ImageIcon();
       // setIconImage(icone.getImage());
            String sql = ("Select (logimagem)as Logo from tbempresa ");
               
            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            if (rs.next()) {
                byte[]img=rs.getBytes("Logo");
                //resize the imageIcon
                ImageIcon Logo= new ImageIcon(img);
               // String Endereco = rs.getString("Endereco");
                Image im =Logo.getImage();
                Image myImg=im.getScaledInstance(jLabelNLogo.getWidth(),jLabelNLogo.getHeight(),Image.SCALE_SMOOTH);
               // Image myImg=im.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
                ImageIcon newImage=new ImageIcon(myImg);
                 jLabelNLogo.setIcon(Logo);
                
            }
               
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro ao buscar a Logo!\nERRO" + error);
        }
         
          
        try {
            String sql = ("Select (data_vencimento)as vencimento from tbvencimento ");

            pst = conexao.prepareStatement(sql);

            ResultSet rs = pst.executeQuery(sql);

            if (rs.last()) {
                char[] vencimento = rs.getString("vencimento").toCharArray();
              
               jLabelLicenca.setText(String.valueOf("Espiração: "+vencimento[0]+""+vencimento[1]+"/"+vencimento[2]+""+vencimento[3]+"/"+vencimento[4]+vencimento[5]+vencimento[6]+vencimento[7]));
               
                jLabelLicenca.setVisible(false);
                String dvencimento = (String.valueOf(" "+vencimento[0]+""+vencimento[1]+"/"+vencimento[2]+""+vencimento[3]+"/"+vencimento[4]+vencimento[5]+vencimento[6]+vencimento[7]));
               
               
//               int divenc=Integer.parseInt(""+vencimento[0]+""+vencimento[1]);
//               int mesvenc=Integer.parseInt(""+vencimento[2]+""+vencimento[3]);
//               int anovenc=Integer.parseInt(""+vencimento[4]+vencimento[5]+vencimento[6]+vencimento[7]);
               SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                Date hoje = new Date();
                //JOptionPane.showMessageDialog(rootPane,df.format(hoje));
                String dataAtual = (String) df.format(hoje);
//               String dvenc=df.format(dvencimento);
              
//             String atual=dataAtual;
//            String venci=dvencimento;
                try {
                    Date data1=df.parse(dataAtual);
                    Date data2=df.parse(dvencimento);
                    long difference=data2.getTime()-data1.getTime();
                    float daysBetween=(difference/(1000*60*60*24));
                    if(daysBetween<1){
                        jLabelEspiracao.setText(String.valueOf("Licença expirada. Solicite uma nova Licença"));
                        jLabelLicenca.setVisible(true);
                    }else{  
                    jLabelEspiracao.setText(String.valueOf("Restam "+daysBetween+" dias pra esta Licença expirar"));
                    }
//                    jLabelLicenca.setVisible(false);
                   
                } catch (Exception e) {
                }
            }
            

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, " Erro do ArrayIndex!\nERRO" + error);
        } 
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBoletimActionPerformed
        // TODO add your handling code here:
         AvaliacaoDoAluno avaliacao = new AvaliacaoDoAluno();
        avaliacao.setVisible(true);
        Desktop.add( avaliacao);
        try {
   avaliacao.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuBoletimActionPerformed

    private void BoletimConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoletimConsultaActionPerformed
        // TODO add your handling code here:
       BoletimConsulta boletim = new BoletimConsulta();
        boletim.setVisible(true);
        Desktop.add( boletim);
         try {
         boletim.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_BoletimConsultaActionPerformed

    private void menFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFuncionariosActionPerformed
        // TODO add your handling code here:
         Funcionarios funcionarios = new Funcionarios();
        funcionarios.setVisible(true);
        Desktop.add( funcionarios);
         try {
          funcionarios.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_menFuncionariosActionPerformed

    private void jMenuItemTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurnosActionPerformed
        // TODO add your handling code here:
         CadastroDePreços turnos = new  CadastroDePreços();
       turnos.setVisible(true);
        Desktop.add(turnos);
        try {
         turnos.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jMenuItemTurnosActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
         String url = "https://www.google.com";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLicencaActionPerformed
        // TODO add your handling code here:
        try { 
         String url = "http://infotokes.tk/fal.html";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_jButtonLicencaActionPerformed

    private void jMenuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoActionPerformed
        // TODO add your handling code here:
        int comfirma = JOptionPane.showConfirmDialog(null, "Confirma a Emissão deste Relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(comfirma==JOptionPane.YES_OPTION){
            try {
                net.sf.jasperreports.engine.JasperPrint print=JasperFillManager.fillReport("lib/report/RelatórioAlunos.jasper",null,conexao);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        
    }//GEN-LAST:event_jMenuItemAlunoActionPerformed

    private void jMenuItemFuncionáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionáriosActionPerformed
        // TODO add your handling code here:
        int comfirma = JOptionPane.showConfirmDialog(null, "Confirma a Emissão deste Relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(comfirma==JOptionPane.YES_OPTION){
            try {
                net.sf.jasperreports.engine.JasperPrint print=JasperFillManager.fillReport("lib/report/Funcionários Tokes.jasper",null,conexao);
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        
        
        
    }//GEN-LAST:event_jMenuItemFuncionáriosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int confirma=JOptionPane.showConfirmDialog(null, "Confirma a Emissão deste Relatório","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            try {
                net.sf.jasperreports.engine.JasperPrint print = JasperFillManager.fillReport("lib/report/Clientes.jasper",null,conexao);
                JasperViewer.viewReport(print,false); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            }

          
            
       
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int confirma=JOptionPane.showConfirmDialog(null, "Confirma a Emissão deste Relatório","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma==JOptionPane.YES_OPTION){
            try {
                net.sf.jasperreports.engine.JasperPrint print = JasperFillManager.fillReport("lib/report/parcelas.jasper",null,conexao);
                JasperViewer.viewReport(print,false); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

         
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USUARIOActionPerformed

    private void jMenuItemValidacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemValidacaoActionPerformed
        // TODO add your handling code here:
        ValidacaoDoSistema valiadacao = new ValidacaoDoSistema();
        valiadacao.setVisible(true);
        Desktop.add( valiadacao);

    }//GEN-LAST:event_jMenuItemValidacaoActionPerformed

    private void jMenuItemProgramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProgramadorActionPerformed
        // TODO add your handling code here:
        GeradorDeSenha gerador = new GeradorDeSenha();
        gerador.setVisible(true);
        Desktop.add( gerador);
    }//GEN-LAST:event_jMenuItemProgramadorActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        // método para chamar a tela usuarios
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
        try {
         usuario.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }     
    }//GEN-LAST:event_menCadUsuActionPerformed

    private void jMenuItemCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdutosActionPerformed
        // TODO add your handling code here:
         CadastroProdutos produto = new CadastroProdutos();
        produto.setVisible(true);
        Desktop.add(produto);
        try {
         produto.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }     
        
    }//GEN-LAST:event_jMenuItemCadProdutosActionPerformed

    private void jMenuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendaActionPerformed
        // TODO add your handling code here:
    TelaVendas venda = new TelaVendas();
        venda.setVisible(true);
        Desktop.add(venda);
        try {
         venda.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
         JOptionPane.showMessageDialog(null, " Erro ao Inicializar o Form!\nERRO" + ex);
    }     
        
        
        
    }//GEN-LAST:event_jMenuItemVendaActionPerformed

    private void jMenuItemPesquiVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquiVendasActionPerformed
        // TODO add your handling code here:
        
        PesquisarVendas Pvenda = new PesquisarVendas();
        Pvenda.setVisible(true);
        Desktop.add(Pvenda);
        try {
         Pvenda.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
         JOptionPane.showMessageDialog(null, " Erro ao Inicializar o Form!\nERRO" + ex);
    }     
        
        
        
    }//GEN-LAST:event_jMenuItemPesquiVendasActionPerformed

    private void jMenuItemBaixaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBaixaVendaActionPerformed
        // TODO add your handling code here:
         BaixaVenda baixa = new BaixaVenda();
        baixa.setVisible(true);
        Desktop.add( baixa);
         try {
         baixa.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItemBaixaVendaActionPerformed

    private void jMenuItemFinancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinancasActionPerformed
        // TODO add your handling code here:
        Financas fin = new Financas();
        fin.setVisible(true);
        Desktop.add( fin);
         try {
         fin.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItemFinancasActionPerformed

    private void jMenuItemCadNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadNotasActionPerformed
        // TODO add your handling code here:
         CadastroNotas notas = new  CadastroNotas();
        notas.setVisible(true);
        Desktop.add( notas);
         try {
         notas.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItemCadNotasActionPerformed

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        // TODO add your handling code here:
         Fornecedores fornece = new  Fornecedores();
        fornece.setVisible(true);
        Desktop.add( fornece);
         try {
         fornece.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jMenuItemMensaldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMensaldadeActionPerformed
        // TODO add your handling code here:
         BaixaParcelas1 parcelas1 = new BaixaParcelas1();
        parcelas1.setVisible(true);
        Desktop.add(parcelas1);
    try {
        parcelas1.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItemMensaldadeActionPerformed

    private void jMenuItemCadLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadLicenceActionPerformed
        // TODO add your handling code here:
        CadastroDeLicenca  licenca = new CadastroDeLicenca ();
      licenca.setVisible(true);
        Desktop.add(licenca);
    try {
        licenca.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
//        CadastroDeLicenca 
    }//GEN-LAST:event_jMenuItemCadLicenceActionPerformed

    private void menCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadOsActionPerformed
        // TODO add your handling code here:
         OrdemDeServicos  os = new OrdemDeServicos ();
       os.setVisible(true);
        Desktop.add( os);
    try {
         os.setMaximum(true); // Vetoed by internalFrame
        // ... possibly add some handling for this case
    } catch (PropertyVetoException ex) {
        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        
    }//GEN-LAST:event_menCadOsActionPerformed
    }
    
    
    
    
     private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/mtsoftware/icones/LOGSOFT_Small-6.png")));
        
    }
    /**
     * @param args the command line arguments
     */
 
    private JDesktopPane intializeDesktop(JDesktopPane Desktop,String imagePath,int scalx,int scaly) {

        // A specialized layered pane to be used with JInternalFrames
        Desktop= new JDesktopPane() {
            ImageIcon icon = new ImageIcon("/br/com/mtsoftware/icones/Schoolsystem.jpg");
            Image image = icon.getImage();

            Image newimage = image.getScaledInstance(scalx, scaly, Image.SCALE_SMOOTH);

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(newimage, 0, 0, this);
            }
        };

        return Desktop;
    }
    
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    /* if (rs.next()) {
                byte[]img=rs.getBytes("Logo");
                //resize the imageIcon
                ImageIcon Logo= new ImageIcon(img);
               // String Endereco = rs.getString("Endereco");
                Image im =Logo.getImage();
                Image myImg=im.getScaledInstance(jLabelLogo.getWidth(),jLabelLogo.getHeight(),Image.SCALE_SMOOTH);
               // Image myImg=im.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
                ImageIcon newImage=new ImageIcon(myImg);
                 jLabelLogo.setIcon(Logo);
                
            }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem BoletimConsulta;
    private javax.swing.JMenu COMERCIAL1;
    public static javax.swing.JDesktopPane Desktop;
    public static javax.swing.JMenu Escola;
    private javax.swing.JMenu MenAju;
    private javax.swing.JMenuItem MenAjuSob1;
    private javax.swing.JMenu MenOpc;
    private javax.swing.JMenuItem MenOpcSai1;
    public static javax.swing.JMenu MenRel;
    private javax.swing.JMenuItem MenRelServ1;
    private javax.swing.JMenuBar Menu1;
    public static javax.swing.JMenu USUARIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLicenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEspiracao;
    private javax.swing.JLabel jLabelHorario;
    public static javax.swing.JLabel jLabelLicenca;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNLogo;
    private javax.swing.JLabel jLabelNif;
    public static javax.swing.JLabel jLabelend;
    public static javax.swing.JMenuItem jMenuBoletim;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAluno;
    public static javax.swing.JMenuItem jMenuItemBaixaVenda;
    public static javax.swing.JMenuItem jMenuItemCadLicence;
    private javax.swing.JMenuItem jMenuItemCadNotas;
    public static javax.swing.JMenuItem jMenuItemCadProdutos;
    public static javax.swing.JMenuItem jMenuItemFinancas;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemFuncionários;
    public static javax.swing.JMenuItem jMenuItemMensaldade;
    public static javax.swing.JMenuItem jMenuItemPesquiVendas;
    public static javax.swing.JMenuItem jMenuItemProgramador;
    private javax.swing.JMenuItem jMenuItemTurnos;
    public static javax.swing.JMenuItem jMenuItemValidacao;
    public static javax.swing.JMenuItem jMenuItemVenda;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel jlabelempresa;
    private java.awt.Label lblData;
    public static java.awt.Label lblUsuario;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenu menCadEmpr;
    public static javax.swing.JMenuItem menCadEmpre;
    private javax.swing.JMenuItem menCadOs;
    public static javax.swing.JMenuItem menCadUsu;
    public static javax.swing.JMenuItem menCadastro;
    public static javax.swing.JMenuItem menClasses;
    public static javax.swing.JMenuItem menContratos;
    public static javax.swing.JMenuItem menFuncionarios;
    public static javax.swing.JMenuItem menPagamentos;
    static javax.swing.JMenu nenCadCli;
    // End of variables declaration//GEN-END:variables

    
   
}
